services:
  # ─────────────────────────────────────────────────────────────
  # Phase 0: Import Execution Snapshot (manual one-shot)
  # ─────────────────────────────────────────────────────────────
  nimbus_import_m:
    image: statusim/nimbus-eth1:master
    container_name: nimbus_import_m
    network_mode: host
    restart: "no"
    volumes:
      - /root/ethereum/execution_m:/data_m
      - /root/ethereum/era_m:/era_m:ro
      - /root/ethereum/era1_m:/era1_m:ro
    command:
      - import
      - --network=mainnet
      - --data-dir=/data_m
      - --era-dir=/era_m
      - --era1-dir=/era1_m
      
  # ─────────────────────────────────────────────────────────────
  # Execution client - Nimbus Execution Node
  # ─────────────────────────────────────────────────────────────
  nimbus_eth1_m:
    image: statusim/nimbus-eth1:master
    container_name: nimbus_eth1_m
    network_mode: host
    restart: unless-stopped
    mem_limit: 16g
    mem_reservation: 8g
    ports:
      - "0.0.0.0:8545:8545/tcp"  # HTTP RPC
      - "30303:30303"            # P2P TCP
      - "30303:30303/udp"        # P2P UDP
    volumes:
      - /root/ethereum/execution_m:/data_m
      - /root/ethereum/jwt_m.hex:/jwt_m.hex:ro
    environment:
      - EXTERNAL_IP=${EXTERNAL_IP}
      - BOOTSTRAP_NODES=${BOOTSTRAP_NODES}
    command:
      - --network=mainnet
      - --nat=extip:${EXTERNAL_IP}
      - --tcp-port=30303
      - --udp-port=30303
      - --discovery=V5
      - --reconnect-interval=5
      - --http-port=8545
      - --http-address=0.0.0.0
      - --rpc
      - --rpc-api=eth,debug
      - --engine-api
      - --engine-api-port=8551
      - --engine-api-address=127.0.0.1
      - --jwt-secret=/jwt_m.hex
      - --data-dir=/data_m
      - --bootstrap-node=$BOOTSTRAP_NODES
      - --num-threads=4
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "nc", "-z", "0.0.0.0", "8545"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  # ─────────────────────────────────────────────────────────────
  # Phase 1: Trusted Node Sync (manual one-shot)
  # ─────────────────────────────────────────────────────────────
  nimbus_sync_m:
    image: statusim/nimbus-eth2:multiarch-latest
    container_name: nimbus_sync_m
    network_mode: host
    restart: "no"
    volumes:
      - /root/ethereum/consensus_m:/data_m
    command:
      - trustedNodeSync
      - --network=mainnet
      - --data-dir=/data_m
      - --trusted-node-url=http://testing.mainnet.beacon-api.nimbus.team

  # ─────────────────────────────────────────────────────────────
  # Phase 2: Nimbus Beacon Node
  # ─────────────────────────────────────────────────────────────
  nimbus_eth2_m:
    image: statusim/nimbus-eth2:multiarch-latest
    container_name: nimbus_eth2_m
    network_mode: host
    restart: unless-stopped
    mem_limit: 10g
    mem_reservation: 6g
    ports:
      - "0.0.0.0:5052:5052/tcp"  # HTTP RPC
      - "9000:9000/tcp"          # P2P TCP
      - "9000:9000/udp"          # P2P UDP
    volumes:
      - /root/ethereum/consensus_m:/data_m
      - /root/ethereum/jwt_m.hex:/jwt_m.hex:ro
    environment:
      - EXTERNAL_IP=${EXTERNAL_IP}
      - BOOTSTRAP_NODES=${BOOTSTRAP_NODES}
    depends_on:
      nimbus_eth1_m:
        condition: service_healthy
    command:
      - --network=mainnet
      - --data-dir=/data_m
      - --el=http://127.0.0.1:8551
      - --jwt-secret=/jwt_m.hex
      - --rest
      - --rest-address=0.0.0.0
      - --rest-port=5052
      - --tcp-port=9000
      - --udp-port=9000
      - --nat=extip:${EXTERNAL_IP}
      - --bootstrap-node=${BOOTSTRAP_NODES}
      - --max-peers=25
      - --num-threads=4
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
